# Generated by Django 4.2.2 on 2023-07-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_station_delete_weather_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='weather_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cod_city', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('precipitation', models.FloatField()),
                ('dry_bulb_temperature', models.FloatField()),
                ('wet_bulb_temperature', models.FloatField()),
                ('high_temperature', models.FloatField()),
                ('low_temperature', models.FloatField()),
                ('relative_humidity', models.FloatField()),
                ('relative_humidity_avg', models.FloatField()),
                ('pressure', models.FloatField()),
                ('sea_pressure', models.FloatField()),
                ('wind_direction', models.FloatField()),
                ('wind_speed_avg', models.FloatField()),
                ('cloud_cover', models.FloatField()),
                ('evaporation', models.FloatField()),
            ],
        ),
    ]
